### ISSUE TITLE
failed to read the model file.

### ISSUE THREAD

**Issue by hufuzhipeng** [openai/shap-e#3] opened 2023-05-05 05:30 UTC
Traceback (most recent call last):
  File "E:\code\ai\shap-e\shapetest\shapetest\shapetest.py", line 11, in <module>
    model = load_model('text300M', device=device)
  File "e:\code\ai\shap-e\shap_e\models\download.py", line 110, in load_model
    model.load_state_dict(load_checkpoint(model_name, device=device, **kwargs))
  File "e:\code\ai\shap-e\shap_e\models\download.py", line 99, in load_checkpoint
    return torch.load(path, map_location=device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive

**Comment by hufuzhipeng** [comment] 2023-05-05 06:16
solved the problem by re-download the file. but met another error:
  File "E:\code\ai\shap-e\shapetest\shapetest\shapetest.py", line 40, in <module>
    display(gif_widget(images))
NameError: name 'display' is not defined

**Comment by unixpickle** [comment] 2023-05-05 20:18
The original issue seems to be a duplicate of https://github.com/openai/shap-e/issues/2

**Closed by unixpickle** 2023-05-05 20:18 UTC
